### ISSUE TITLE
Column missing / wrong table used

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-server#21]
[CognicityServer.js#L126](https://github.com/smart-facility/cognicity-server/blob/2.0.x/CognicityServer.js#L126) introduced in 649badd throws the following errors in conjunction with [cognicity-schema/schema.sql in 2.0.x](https://github.com/smart-facility/cognicity-schema/blob/2.0.x/schema.sql) as applied to a fresh database using [fresh-cognicity-database.sh](https://gist.github.com/matthewberryman/03e56417f9bc8fa7cdd1):
2015-08-24T00:37:49.676Z - error: dataQuery: Database query failed, column "source" does not exist, queryObject={"text":"SELECT 'FeatureCollection' As type, array_to_json(array_agg(f)) As features FROM (SELECT 'Feature' As type, ST_AsGeoJSON(lg.the_geom)::json As geometry, row_to_json( (SELECT l FROM (SELECT pkey, created_at at time zone 'ICT' created_at, source, url, image_url, title, text)  As l) ) As properties FROM tweet_reports As lg WHERE created_at >= to_timestamp($1) AND created_at <= to_timestamp($2) ORDER BY created_at DESC LIMIT $3 ) As f ;","values":["-1","1440376669",null]}
2015-08-24T00:37:49.677Z - error: Express error: undefined, Database query error, Error: Database query error
    at null.callback (/home/matthew/cognicity-server/[CognicityServer.js:78](https://github.com/smart-facility/cognicity-server/blob/2.0.x/CognicityServer.js#L126):16)
    at Query.handleError (/home/matthew/cognicity-server/node_modules/pg/lib/query.js:99:17)
    at null.<anonymous> (/home/matthew/cognicity-server/node_modules/pg/lib/client.js:176:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/home/matthew/cognicity-server/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)

I am guessing you probably want to update [config.js#L87](https://github.com/smart-facility/cognicity-server/blob/2.0.x/config.js#L87) to refer to the [all_reports table](https://github.com/smart-facility/cognicity-schema/blob/2.0.x/schema.sql#L239) or otherwise update tweet_reports (although why have a source column for that). Something else to consider is whether there are any unused tables with all the other new ones introduced.

**Comment by talltom** [comment]
You are right, need to reference all_reports table...but this has broken Travis for some reason.

https://travis-ci.org/smart-facility/cognicity-server/builds/87835863

**Comment by matthewberryman** [comment]
@talltom your cognicity-server commit references a petajakarta commit doesn't exist on github yet. Please push all local commits and once this passes travis I'll close.

**Comment by talltom** [comment]
My bad. Fixed this now.

**Comment by matthewberryman** [comment]
Tested 05231a6  and confirmed it's all working for me.
